version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - nginx
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sebastian
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis


volumes:
  mongo-db: